### ISSUE TITLE
[feature]: 로그아웃 및 회원 탈퇴 기능 추가합니다

### ISSUE THREAD

**Issue by lee02029** [Chilli-Saewoo/Roll-in#141]
### Feature 설명

설정창에서 로그아웃 및 회원 탈퇴 기능을 추가합니다.
일단 생각해야 되는 부분은 회원 탈퇴 기능에서 아래의 데이터를 제거 해주어야 합니다. @yeahaluu 확인 부탁드립니다.
1.users에 해당하는 user_uid값을 체크(계속 참조해야되서 삭제를 마지막으로 미루겠습니다!)
<img width="597" alt="스크린샷 2022-11-28 오전 10 14 02" src="https://user-images.githubusercontent.com/80015108/204171684-12e2efee-921b-48ea-b753-5f3070c0f2ae.png">
2. userGroups에 해당하는 user_uid값을 체크하고 현재 참여중인 그룹을 확인
<img width="588" alt="스크린샷 2022-11-28 오전 10 14 41" src="https://user-images.githubusercontent.com/80015108/204171743-4c7f81e4-2597-477e-9fa9-a7c1f2e25ea1.png">
3. 그뒤에 GroupUsers에서 해당하는 그룹 group_UUID를 체크 한 후 participants에 들어가서 해당하는 user_uid값 삭제
<img width="610" alt="스크린샷 2022-11-28 오전 10 15 09" src="https://user-images.githubusercontent.com/80015108/204171781-a262d819-aa94-4bf0-b483-4a604c8c5834.png">
4. 현재 1명인 그룹에서 user가 삭제되어 groupUsers/uid/partcipants가 0명이 되는 경우 groupUsers와 groups에서 해당 그룹 삭제
<img width="787" alt="스크린샷 2022-11-28 오후 5 01 35" src="https://user-images.githubusercontent.com/80015108/204224571-91b990e2-a951-45b2-a68c-1f8e8c65ee29.png">
5. userGroups으로 가서 해당하는 user_uid값 삭제
<img width="795" alt="스크린샷 2022-11-28 오후 5 01 58" src="https://user-images.githubusercontent.com/80015108/204224630-15396429-add3-463d-a231-b711dbb15363.png">
6. users에 해당하는 user_uid값을 삭제
<img width="748" alt="스크린샷 2022-11-28 오후 5 02 13" src="https://user-images.githubusercontent.com/80015108/204224686-b7c0c9af-ada5-4279-ad67-cb3ea6a696e3.png">

로그아웃 부분은 아래의 코드 추가후 rootViewController 변경 예정입니다.
`try! FirebaseAuth.Auth.auth().signOut()`

### 예상 작업 기간

~11.28

**Comment by yeahaluu** [comment]
회원이 탈퇴할 경우 2번의 userGroups에 user_uid도 삭제해줘야 할 것 같습니다! 생각하신 부분일 것 같은데 명시해주시면 더 좋을 것 같아요😊

**Comment by lee02029** [comment]
> 회원이 탈퇴할 경우 2번의 userGroups에 user_uid도 삭제해줘야 할 것 같습니다! 생각하신 부분일 것 같은데 명시해주시면 더 좋을 것 같아요😊

아래의 플로우로 수정하겠습니다! 확인부탁드려요😃
1. users에 해당하는 user_uid값을 체크(계속 참조해야되서 삭제를 마지막으로 미루겠습니다!)
2. userGroups에 해당하는 user_uid값을 체크하고 현재 참여중인 그룹을 확인
3.  그뒤에 GroupUsers에서 해당하는 그룹 group_UUID를 체크 한 후 participants에 들어가서 해당하는 user_uid값 삭제
4. 현재 1명인 그룹에서 user가 삭제되어 groupUsers/uid/partcipants가 0명이 되는 경우 groupUsers와 groups에서 해당 그룹 삭제
5. userGroups으로 가서 해당하는 user_uid값 삭제
6. users에 해당하는 user_uid값을 삭제

**Comment by yeahaluu** [comment]
> > 회원이 탈퇴할 경우 2번의 userGroups에 user_uid도 삭제해줘야 할 것 같습니다! 생각하신 부분일 것 같은데 명시해주시면 더 좋을 것 같아요😊
> 
> 아래의 플로우로 수정하겠습니다! 확인부탁드려요😃
> 
> 1. users에 해당하는 user_uid값을 체크(계속 참조해야되서 삭제를 마지막으로 미루겠습니다!)
> 2. userGroups에 해당하는 user_uid값을 체크하고 현재 참여중인 그룹을 확인
> 3. 그뒤에 GroupUsers에서 해당하는 그룹 group_UUID를 체크 한 후 participants에 들어가서 해당하는 user_uid값 삭제
> 4. 현재 1명인 그룹에서 user가 삭제되어 groupUsers/uid/partcipants가 0명이 되는 경우 groupUsers와 groups에서 해당 그룹 삭제
> 5. userGroups으로 가서 해당하는 user_uid값 삭제
> 6. users에 해당하는 user_uid값을 삭제

너무 좋습니다!!👍👍 하루짱
