### ISSUE TITLE
[feature]: Group에 참가하는 FireStore 업데이트 로직

### ISSUE THREAD

**Issue by feldblume5263** [Chilli-Saewoo/Roll-in#92]
### Feature 설명

@yeahaluu  확인 부탁드립니다!

1. `userGroups`의 해당 Userid 문서의 division 항목에 새 group 추가

<img width="426" alt="스크린샷 2022-11-13 오후 7 36 55" src="https://user-images.githubusercontent.com/53016167/201517371-0df0d278-c4be-4079-a35c-1cb29a2a0ae4.png">

2. `groupUsers` 의 새로 들어가게 될 group uuid 의 participants 항목에 본인 uuid 추가
userNickname도 추가
<img width="503" alt="스크린샷 2022-11-13 오후 7 39 32" src="https://user-images.githubusercontent.com/53016167/201517453-44171091-4a9b-477d-8e8a-d59aa99be72c.png">

### 예상 작업 기간

1시간 30분 정도

**Comment by yeahaluu** [comment]
2번의 user_uid에 userNickname도 추가해야 합니다👍😊

**Comment by feldblume5263** [comment]
> 2번의 user_uid에 groupNickname도 추가해야 합니다👍😊

핫 감사합니다 선생님ㅎㅎ
